// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(

    apiKey: 'AIzaSyCBIw7dshbRqatOfiCMY6vcHwkID13JQZw',
    appId: '1:588678431791:web:2d29d443305966a9ea72da',
    messagingSenderId: '588678431791',
    projectId: 'tu-vung-tienganh',
    authDomain: 'tu-vung-tienganh.firebaseapp.com',
    databaseURL: 'https://tu-vung-tienganh-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tu-vung-tienganh.firebasestorage.app',
    measurementId: 'G-2YWCGWP32S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgc2KJ5eVk8f49xi19y5m1WmmgisVaqF0',
    appId: '1:588678431791:android:4b347df3f33f5bdcea72da',
    messagingSenderId: '588678431791',
    projectId: 'tu-vung-tienganh',
    databaseURL: 'https://tu-vung-tienganh-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tu-vung-tienganh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoe3BW7NN71bJH-pVHbPQ2fuuUMK_Btk0',
    appId: '1:588678431791:ios:8afa1131aa0804f4ea72da',
    messagingSenderId: '588678431791',
    projectId: 'tu-vung-tienganh',
    databaseURL: 'https://tu-vung-tienganh-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tu-vung-tienganh.firebasestorage.app',

    iosBundleId: 'com.example.appTiengAnh',
  );

  static const FirebaseOptions macos = FirebaseOptions(

    apiKey: 'AIzaSyDoe3BW7NN71bJH-pVHbPQ2fuuUMK_Btk0',
    appId: '1:588678431791:ios:8afa1131aa0804f4ea72da',
    messagingSenderId: '588678431791',
    projectId: 'tu-vung-tienganh',
    databaseURL: 'https://tu-vung-tienganh-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tu-vung-tienganh.firebasestorage.app',

    iosBundleId: 'com.example.appTiengAnh',
  );

  static const FirebaseOptions windows = FirebaseOptions(

    apiKey: 'AIzaSyCBIw7dshbRqatOfiCMY6vcHwkID13JQZw',
    appId: '1:588678431791:web:fea5ac1d3b8edb5eea72da',
    messagingSenderId: '588678431791',
    projectId: 'tu-vung-tienganh',
    authDomain: 'tu-vung-tienganh.firebaseapp.com',
    databaseURL: 'https://tu-vung-tienganh-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tu-vung-tienganh.firebasestorage.app',
    measurementId: 'G-K60W35Z646',
  );
}

